Code/QiBuBlog.WWW/Areas/Manage/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QiBuBlog.WWW.Controllers;

namespace QiBuBlog.WWW.Areas.Manage.Controllers
{
    public class ArticleController : BaseController
    {
        //
        // GET: /Manage/Article/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Areas/Manage/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QiBuBlog.WWW.Controllers;

namespace QiBuBlog.WWW.Areas.Manage.Controllers
{
    public class CategoryController : BaseController
    {
        //
        // GET: /Manage/Category/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Areas/Manage/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QiBuBlog.WWW.Controllers;

namespace QiBuBlog.WWW.Areas.Manage.Controllers
{
    public class CommentController : BaseController
    {
        //
        // GET: /Manage/Comment/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Areas/Manage/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QiBuBlog.WWW.Controllers;

namespace QiBuBlog.WWW.Areas.Manage.Controllers
{
    public class DashboardController : BaseController
    {
        //
        // GET: /Manage/Dashboard/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Areas/Manage/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QiBuBlog.WWW.Controllers;

namespace QiBuBlog.WWW.Areas.Manage.Controllers
{
    public class SetupController : BaseController
    {
        //
        // GET: /Manage/Setup/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Areas/Manage/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QiBuBlog.WWW.Controllers;

namespace QiBuBlog.WWW.Areas.Manage.Controllers
{
    public class UserController : BaseController
    {
        //
        // GET: /Manage/User/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Controllers/ArticleController.cs
using QiBuBlog.Service;
using QiBuBlog.Util;
using System.Web.Mvc;

namespace QiBuBlog.WWW.Controllers
{
    public class ArticleController : BaseController
    {
        //
        // GET: /Article/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail(string id)
        {
            var model = ArticleService.Instance.GetModelById(id);
            return View(model);
        }
    }
}

Code/QiBuBlog.WWW/Controllers/BaseController.cs
using System.Web.Mvc;

namespace QiBuBlog.WWW.Controllers
{
    [SelfOnly]
    public class BaseController : Controller
    {

    }
}

Code/QiBuBlog.WWW/Controllers/HomeController.cs
using QiBuBlog.Service;
using QiBuBlog.Util;
using System.Web.Mvc;

namespace QiBuBlog.WWW.Controllers
{
    public class HomeController : BaseController
    {
        //
        // GET: /Home/

        public ActionResult Index(string id, int? page)
        {
            ViewBag.CurrentPosition = id;
            var categoryId = string.Empty;
            if (!string.IsNullOrWhiteSpace(id))
            {
                var cId = MenuService.Instance.GetMenuCategoryId(id);
                if (!string.IsNullOrWhiteSpace(cId))
                {
                    categoryId = cId;
                }
            }
            var articleData = ArticleService.Instance.GetPageList(categoryId, page ?? 1, id == "7e83d75879f540cc84f662db7a1d4178" ? true : false);
            return View(articleData);
        }
    }
}

Code/QiBuBlog.WWW/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QiBuBlog.WWW.Controllers
{
    public class InfoController : BaseController
    {
        //
        // GET: /Info/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Code/QiBuBlog.WWW/Controllers/LoginController.cs
using QiBuBlog.Entity;
using QiBuBlog.Service;
using QiBuBlog.Util;
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace QiBuBlog.WWW.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCaptcha()
        {
            var captcha = new Captcha(4);
            CaptchaManager.Write("login", captcha.Value);
            Response.Cookies.Add(new HttpCookie("QiBu_Captcha", captcha.Value));
            Image image = captcha.CreateImage(
                Color.FromArgb(
                    Convert.ToInt32(255),
                    Convert.ToInt32(255),
                    Convert.ToInt32(255)
                ), 170, 15, 4, 5
            );
            var stream = new MemoryStream();
            image.Save(stream, ImageFormat.Png);
            stream.Close();
            return File(stream.GetBuffer(), @"image/png");
        }

        public JsonResult Authority(string userName, string password)
        {
            var user = UserService.UserLogin(userName, password);
            if (user != null)
            {
                user.Password = null;
                FormLoginHelper<User>.Set(user, true);
            }
            else
            {
                
            }
            return Json(null);
        }

        [SelfOnly]
        public ActionResult Logout()
        {
            FormLoginHelper<User>.Logout("/login");
            return View();
        }
    }
}

Code/QiBuBlog.WWW/Views/Article/Detail.cshtml
@{
    ViewBag.Title = Model.Title;
}
<link href="@Url.Content("~/Content/article-detail.css")" rel="stylesheet" type="text/css" />
<div class="main">
    <div class="inner">
        <article class="article">
            <header>
                <h1 class="article-title">@Model.Title</h1>
                <ul class="article-info clearfix">
                    <li class="article-posttime">
                        <address>@Model.CreateUserId</address>
                        发表于
                        <time datetime="@Model.CreateTime.ToString("yyyy-MM-ddThh:mm:sszzz")">@Model.CreateTime.ToString("yyyy-MM-dd HH:mm")</time>
                    </li>
                    <li>分类：<a href="@Url.Action("Index", new { id = Model.CategoryId })">@Model.CategoryId</a></li>
                    <li>浏览次数：@Model.ViewCount</li>
                    <li>评论次数：<span class="comment-count">@Model.CommentCount</span></li>
                </ul>
            </header>
            <div class="article-content">@Html.Raw(Model.Content)</div>
        </article>

        @if (true)
        {
            <section id="comment-list" class="comment-list">
                <h2 class="titlebar">评论（共<em class="comment-count">@Model.CommentCount</em>条）</h2>
                <div></div>
            </section>

            <div class="comment-form">
                <h2 class="titlebar">参与讨论</h2>
                <form action="@Url.Action("Post", "Comment", null)" method="post" class="clearfix">
                    @if (ViewBag.User == null)
                    {
                        <div class="col-l">
                            <p class="form-field textbox-with-label">
                                <textarea class="form-text" name="Content" id="Content" rows="5" cols="40" style="height: 125px;"></textarea><label for="Content">请填写评论内容 <span class="required">*</span></label>
                            </p>
                        </div>
                        <div class="col-r">
                            <p class="form-field textbox-with-label">
                                <input type="text" name="AuthorName" id="AuthorName" class="form-text" maxlength="20" /><label for="AuthorName">您的称呼 <span class="required">*</span></label>
                            </p>
                            <p class="form-field textbox-with-label">
                                <input type="text" name="Email" id="Email" class="form-text" /><label for="Email">Email（选填，保密）</label>
                            </p>
                            <p class="form-field textbox-with-label">
                                <input type="text" name="HomePage" id="HomePage" class="form-text" /><label for="HomePage">个人博客或主页（选填）</label>
                            </p>
                            <div class="captcha">
                                <span class="form-field textbox-with-label">
                                    <input type="text" name="captcha" id="captcha" class="form-text" maxlength="4" /><label for="captcha">验证码  <span class="required">*</span></label>
                                </span>
                                <img data-src="@Url.Content("/Login/GetCaptcha")" data-bgcolor="255,255,255" data-formname="comment" class="captcha-img" alt="点击更换验证码" />
                            </div>
                            <p class="form-button">
                                <input type="submit" value="发 表" class="button" />
                            </p>
                        </div>
                    }
                    else
                    {
                        <p class="form-field textbox-with-label">
                            <textarea class="form-text" name="Content" id="Content" rows="5" cols="40"></textarea><label for="Content">请填写评论内容 <span class="required">*</span></label>
                        </p>
                        <p class="comment-user">以身份 <strong>@ViewBag.User.DisplayName</strong> 发表评论</p>
                        <p class="form-button">
                            <input type="submit" value="发 表" class="button" />
                        </p>
                    }
                </form>
            </div>
        }

        <div class="adjacent-articles">
            
        </div>
    </div>
</div>

<aside class="sidebar">

</aside>

@section Script{
    <script type="text/javascript" src="@Url.Content("~/Scripts/sns-share.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/captcha.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/comment.js")"></script>
}

Code/QiBuBlog.WWW/Views/Article/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Code/QiBuBlog.WWW/Views/Home/Index.cshtml
@using System.Globalization;
@{
    ViewBag.Title = "Home";
}
<div class="main">
    <div class="inner">
        @if (Model.TotalRecord > 0)
        {
            foreach (var article in Model.Data)
            {
                var routeValues = new { id = article.ArticleId };
                var postTime = article.CreateTime;
                <article class="article">
                    <header>
                        <time datetime="@postTime.ToString("yyyy-MM-ddThh:mm:sszzz")" class="article-postdate"><span class="day">@postTime.Day</span>@postTime.ToString("MMM", CultureInfo.CreateSpecificCulture("zh-CN")).ToUpper()</time>
                        <h2 class="article-title"><a href="@Url.Action("detail", "article", routeValues)">@article.Title</a></h2>
                        <ul class="clearfix">
                            <li>分类：<a href="@Url.Action("index", new { id = article.CategoryId })">@article.CategoryId</a></li>
                            <li>浏览次数：<a href="@Url.Action("detail", "article", routeValues)">@article.ViewCount</a></li>
                            <li>评论次数：<a href="@Url.Action("detail", "article", routeValues)#comment-list">@article.CommentCount</a></li>
                        </ul>
                    </header>
                    <div class="article-content">@Html.Raw(article.Summary)</div>
                    <footer>
                        <ul class="clearfix">
                            <li class="article-posttime">
                                <address>@article.CreateUserId</address> 发表于
                                <time datetime="@postTime.ToString("yyyy-MM-ddThh:mm:sszzz")">@postTime.ToString("yyyy-M-d H:mm")</time>
                            </li>
                            <li class="article-entry"><a href="@Url.Action("detail", "article", routeValues)">阅读全文 &raquo;</a></li>
                        </ul>
                    </footer>
                </article>
            }
        }
    </div>
</div>

<aside class="sidebar">
    @{
        Html.RenderPartial("SidebarLinks");
    }
</aside>

Code/QiBuBlog.WWW/Views/Login/Index.cshtml
@{
    ViewBag.Title = "登录";
}
<link href="~/Style/css/login.css" rel="stylesheet" />
<form id="login-form" class="login-form" action="@Url.Content("/Login/Authority")" method="post">
    <fieldset>
        <legend>用户登录</legend>
        <p><label for="userName">用户名</label></p>
        <p><input id="userName" name="userName" type="text" size="25" /></p>
        <p><label for="password">密　码</label></p>
        <p><input id="password" name="password" type="password" size="25" /></p>
        <p><label for="captcha">验证码</label></p>
        <p class="captcha">
            <input id="captcha" name="captcha" type="text" size="4" maxlength="6" />
            <img data-src="@Url.Content("/Login/GetCaptcha")" data-bgcolor="255,255,255" data-formname="login" alt="点击更换验证码" class="captcha-img" />
            <input type="submit" value="登 录" />
        </p>
        @if (!string.IsNullOrEmpty(ViewBag.Redirect))
        {
            <input type="hidden" name="redirect" value="@ViewBag.Redirect" />
        }
    </fieldset>
</form>
<script src="~/Style/js/jquery.js"></script>
<script src="~/Style/js/jquery.validate.js"></script>
<script src="~/Style/js/captcha.js"></script>
<script type="text/javascript">//<![CDATA[
    new Captcha($("p.captcha"));

    $("#login-form").validate({
        flow: [
            { fields: "userName", errorText: "用户名不能为空" },
            { fields: "password", errorText: "密码不能为空" },
            { fields: "captcha", errorText: "验证码不能为空" }
        ]
    });

    $("#userName").focus();
//]]></script>

Code/QiBuBlog.WWW/Views/Shared/SidebarArticle.cshtml
@model QiBuBlog.Entity.Article
@if (Model != null)
{
<section>
    <h2 class="titlebar">推荐文章</h2>
    <ol class="sidebar-articlelist">
    @foreach (var article in Model)
    {
        <li><a href="@Url.Action("Detail", new { id = article.ArticleId })" target="_blank">@article.Title</a></li>
    }
    </ol>
</section>
}

Code/QiBuBlog.WWW/Views/Shared/SidebarLinks.cshtml
 @if (ViewBag.LinkList != null)
{
<section class="sidebar-links">
    <h2 class="titlebar">友情链接</h2>
    <dl class="clearfix">
@foreach (var link in ViewBag.LinkList)
{
        <dt><a href="@link.LinkUrl" target="_blank">@link.LinkName</a></dt>
        <dd>@link.Description</dd>
}
    </dl>
</section>
}

Code/QiBuBlog.WWW/Views/Shared/SidebarRank.cshtml
@model TidyBlog.Entity.Article[]

@if (Model != null)
{
<section class="sidebar-articlerank">
    <h2 class="titlebar">@(ViewBag.CurrentPosition.CategoryId == 0 ? String.Empty : ViewBag.CurrentPosition.CategoryName + " ")阅读排行</h2>
    <ol class="sidebar-articlelist">
    @foreach (var article in Model)
    {
        <li class="clearfix">
            <div class="sidebar-articlerank-viewcount">@article.ViewCount</div>
            <div class="sidebar-articlerank-title"><a href="@Url.Action("Detail", "Article", new { id = article.ArticleId })" target="_blank">@article.Title</a></div>
        </li>
    }
    </ol>
</section>
}

Code/QiBuBlog.WWW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/Content/Images/favicon.ico" />
    <link href="@Url.Content("~/Content/pub.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <header id="header" class="header">
        <div class="boundary">
            <h1 class="logo">
                <a href="http://@ViewBag.Setup.SiteDomain">
                    <img src="@Url.Content("~/Content/Images/logo.png")" alt="@ViewBag.Setup.SiteName" />
                </a>
            </h1>
            <nav class="global-nav">
                <ul>
                    @foreach (var m in ViewBag.Menu)
                    {
                        <li @Html.Raw(ViewBag.CurrentPosition != null ? (m.MenuId == ViewBag.CurrentPosition ? " class=\"current\"" : string.Empty) : (m.MenuName == "首页"?" class=\"current\"" : string.Empty))><a href="@Url.Action("index", "home", new { id = m.MenuId })">@m.MenuName</a></li>
                    }
                </ul>
            </nav>
        </div>
    </header>
    <div class="body clearfix">
        <div class="boundary">@RenderBody()</div>
    </div>
    <footer id="footer" class="footer">
        <div class="boundary clearfix">
            <nav>
                当前位置：
                <span id="current-position" class="current-position">首页</span>
                <ul id="express-nav" class="express-nav">
                    @foreach (var m in ViewBag.Menu)
                    {
                        <li><a href="#">@m.MenuName</a></li>
                    }
                </ul>
            </nav>
            @if (ViewBag.User != null)
            {

            }
            <div class="copyright">Copyright &copy; 2009-@DateTime.UtcNow.ToString("yyyy") <a href="http://@ViewBag.Setup.SiteDomain">@ViewBag.Setup.SiteName</a></div>
        </div>
    </footer>
    <script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/pub.js")" type="text/javascript"></script>
    @RenderSection("Script", false)
</body>
</html>